import { mergeData, removeItems } from '../src';

import { MetaDataItem } from '../src/reduxHelperTypes';

describe('Test MergeDataProps', () => {
  test('merge object with array prop', () => {
    const original = {
      includeArchived: false,
      searchText: null,
      orderBy: null,
      direction: 'Asc',
      pageIndex: 0,
      pageSize: 10,
      totalItems: 9992,
      totalPage: 1000,
      items: [
        {
          code: 'CSYY100001',
          companyName: 'chdhfjfjgfgjfj',
          title: null,
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: '.  ',
          displayName: 'tdrydrydrydr',
          billingAddress: null,
          shippingAddress: null,
          email: null,
          phone: null,
          mobile: null,
          fax: null,
          taxNo: null,
          otherDetails: null,
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 1,
          createdBy: 'Tuan',
          createdOn: '2018-10-12T03:34:54.2364397+00:00',
          updatedBy: 'Tuan',
          updatedOn: '2018-10-12T03:35:20.8541415+00:00',
          isDeleted: false,
          rowVersion: 'AAAAAAADG1U=',
          userName: null
        },
        {
          code: 'CS20181013327',
          companyName: 'Dibbert, Funk and Cremin',
          title: 'Miss',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Miss.  ',
          displayName: 'Strosin, Wuckert and Deckow',
          billingAddress: '45022 Muller Extension, Lucianoton, Togo',
          shippingAddress: '879 Yundt Springs, Nitzscheside, Tokelau',
          email: 'Wilburn88@hotmail.com',
          phone: '543.345.2302 x02094',
          mobile: '1-708-960-8951',
          fax: '1-322-862-3812 x406',
          taxNo: 'TA20181013328',
          otherDetails:
            'zero administration invoice connecting Heights interactive content Squares bluetooth invoice back-end',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174189,
          createdBy: "Jodie O'Connell",
          createdOn: '2018-10-12T13:27:41.5307907+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaVw=',
          userName: null
        },
        {
          code: 'CS20181013329',
          companyName: 'Stanton, Monahan and Gorczany',
          title: 'Mrs.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Mrs..  ',
          displayName: 'Turner, Gusikowski and Cronin',
          billingAddress: '1838 Jairo Union, Boehmport, Macao',
          shippingAddress:
            '1684 Madie Union, Lueilwitzborough, Russian Federation',
          email: 'Ally_Cummerata31@gmail.com',
          phone: '526-233-8932 x52496',
          mobile: '1-232-389-5217 x3238',
          fax: '(247) 304-5150 x9353',
          taxNo: 'TA20181013330',
          otherDetails:
            "Pa'anga primary Garden, Clothing & Tools one-to-one zero defect Shoes Incredible Granite Chair 5th generation TCP circuit",
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174190,
          createdBy: 'Leland Bahringer',
          createdOn: '2018-10-12T13:27:41.5308604+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaV0=',
          userName: null
        },
        {
          code: 'CS20181013331',
          companyName: 'Bode, Marks and Schamberger',
          title: 'Mrs.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Mrs..  ',
          displayName: 'Konopelski, Lehner and Jaskolski',
          billingAddress: '58795 Schamberger Mill, Leuschketown, Niger',
          shippingAddress:
            '350 Aurelie Creek, Pouroshaven, Trinidad and Tobago',
          email: 'Gino.White38@yahoo.com',
          phone: '1-587-480-9850',
          mobile: '663-556-8274 x941',
          fax: '(886) 228-9503 x33228',
          taxNo: 'TA20181013332',
          otherDetails:
            'grey pink whiteboard Games parse Strategist XML invoice Mountains pixel',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174191,
          createdBy: 'Ally Mills',
          createdOn: '2018-10-12T13:27:41.5309288+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaV4=',
          userName: null
        },
        {
          code: 'CS20181013333',
          companyName: 'Satterfield, Altenwerth and Bartell',
          title: 'Ms.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Ms..  ',
          displayName: 'Balistreri, Schultz and Bashirian',
          billingAddress: '692 Ottilie Track, VonRuedenchester, Malta',
          shippingAddress: '2177 Orn Park, Hesselhaven, Yemen',
          email: 'Halie_Abbott67@hotmail.com',
          phone: '936.816.1040',
          mobile: '335.790.9959',
          fax: '487-277-9433 x744',
          taxNo: 'TA20181013334',
          otherDetails:
            'silver synergy Cordoba Oro protocol virtual Investment Account bandwidth California reciprocal Ghana',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174192,
          createdBy: 'Nikolas Jakubowski',
          createdOn: '2018-10-12T13:27:41.5309972+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaV8=',
          userName: null
        },
        {
          code: 'CS20181013335',
          companyName: 'Bailey, Beier and Monahan',
          title: 'Miss',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Miss.  ',
          displayName: "Friesen, Hand and D'Amore",
          billingAddress: '35622 Stanley Hill, Predovicbury, Hong Kong',
          shippingAddress: '7656 Cameron Roads, West Melvina, Albania',
          email: 'Camilla.Gottlieb18@gmail.com',
          phone: '565.993.4665 x58126',
          mobile: '328.563.6036',
          fax: '1-804-663-3470 x100',
          taxNo: 'TA20181013336',
          otherDetails:
            'Zambian Kwacha Handcrafted Wooden Gloves Senior Handcrafted Steel Sausages Incredible Credit Card Account Checking Account Personal Loan Account SCSI Louisiana',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174193,
          createdBy: 'Bo Hessel',
          createdOn: '2018-10-12T13:27:41.5310825+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWA=',
          userName: null
        },
        {
          code: 'CS20181013337',
          companyName: 'Fadel, Huels and Mueller',
          title: 'Ms.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Ms..  ',
          displayName: 'Crist, Reynolds and Williamson',
          billingAddress: '055 Nestor Street, New Myaland, United Kingdom',
          shippingAddress: '85823 Richie Loaf, Harveychester, Senegal',
          email: 'Kayley96@hotmail.com',
          phone: '245-807-2411 x55163',
          mobile: '1-503-441-7141 x735',
          fax: '1-529-216-6378 x797',
          taxNo: 'TA20181013338',
          otherDetails:
            'Saint Helena Pound Cambridgeshire Officer Missouri synthesize Incredible Manager Data parsing Licensed Fresh Chicken',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174194,
          createdBy: 'Lazaro Botsford',
          createdOn: '2018-10-12T13:27:41.531157+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWE=',
          userName: null
        },
        {
          code: 'CS20181013339',
          companyName: 'Streich, Douglas and Upton',
          title: 'Miss',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Miss.  ',
          displayName: 'Kertzmann, Deckow and Bashirian',
          billingAddress: '64161 Presley Center, New Kristian, Swaziland',
          shippingAddress: '133 Shane Alley, Lake Gertrude, Jordan',
          email: 'Muriel.Kautzer@gmail.com',
          phone: '(654) 203-1184 x26287',
          mobile: '(602) 385-7275 x07019',
          fax: '699-868-5186 x011',
          taxNo: 'TA20181013340',
          otherDetails:
            'Tasty Division Buckinghamshire Silver Agent Tasty Fresh Shirt envisioneer Small Internal Expressway',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174195,
          createdBy: 'Edna Gottlieb',
          createdOn: '2018-10-12T13:27:41.5312274+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWI=',
          userName: null
        },
        {
          code: 'CS20181013341',
          companyName: 'Morar, Jast and Green',
          title: 'Mrs.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Mrs..  ',
          displayName: 'Pouros, Koelpin and Jacobi',
          billingAddress: '687 Anika Mountain, Schadenport, Comoros',
          shippingAddress: '586 Cormier Hill, Jarredburgh, Andorra',
          email: 'Wilfrid.Ryan@gmail.com',
          phone: '1-705-845-9412',
          mobile: '548-599-6998',
          fax: '816.848.8674 x180',
          taxNo: 'TA20181013342',
          otherDetails:
            'Intuitive Lead SCSI stable Dynamic interfaces Bedfordshire bi-directional Cambridgeshire parsing',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174196,
          createdBy: 'Sienna Lehner',
          createdOn: '2018-10-12T13:27:41.5312962+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWM=',
          userName: null
        },
        {
          code: 'CS20181013343',
          companyName: 'Brekke, Grimes and Carter',
          title: 'Miss',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Miss.  ',
          displayName: 'Grant, Kub and Rice',
          billingAddress: '9796 Maggio Harbor, Bernardside, Martinique',
          shippingAddress: '8177 Laura Heights, New Gladyceland, Chile',
          email: 'Lance33@hotmail.com',
          phone: '915.915.7832 x086',
          mobile: '1-886-449-2542 x591',
          fax: '511.482.1394',
          taxNo: 'TA20181013344',
          otherDetails:
            'Park 3rd generation copy optical Sports Awesome Fresh Chips Auto Loan Account Usability New Jersey Money Market Account',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174197,
          createdBy: 'Anibal Bednar',
          createdOn: '2018-10-12T13:27:41.5313663+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWQ=',
          userName: null
        }
      ]
    };

    const latest = {
      includeArchived: false,
      searchText: null,
      orderBy: null,
      direction: 'Asc',
      pageIndex: 0,
      pageSize: 20,
      totalItems: 9992,
      totalPage: 500,
      items: [
        {
          code: 'CSYY100001',
          companyName: 'chdhfjfjgfgjfj',
          title: null,
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: '.  ',
          displayName: 'tdrydrydrydr',
          billingAddress: null,
          shippingAddress: null,
          email: null,
          phone: null,
          mobile: null,
          fax: null,
          taxNo: null,
          otherDetails: null,
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 1,
          createdBy: 'Tuan',
          createdOn: '2018-10-12T03:34:54.2364397+00:00',
          updatedBy: 'Tuan',
          updatedOn: '2018-10-12T03:35:20.8541415+00:00',
          isDeleted: false,
          rowVersion: 'AAAAAAADG1U=',
          userName: null
        },
        {
          code: 'CS20181013327',
          companyName: 'Dibbert, Funk and Cremin',
          title: 'Miss',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Miss.  ',
          displayName: 'Strosin, Wuckert and Deckow',
          billingAddress: '45022 Muller Extension, Lucianoton, Togo',
          shippingAddress: '879 Yundt Springs, Nitzscheside, Tokelau',
          email: 'Wilburn88@hotmail.com',
          phone: '543.345.2302 x02094',
          mobile: '1-708-960-8951',
          fax: '1-322-862-3812 x406',
          taxNo: 'TA20181013328',
          otherDetails:
            'zero administration invoice connecting Heights interactive content Squares bluetooth invoice back-end',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174189,
          createdBy: "Jodie O'Connell",
          createdOn: '2018-10-12T13:27:41.5307907+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaVw=',
          userName: null
        },
        {
          code: 'CS20181013329',
          companyName: 'Stanton, Monahan and Gorczany',
          title: 'Mrs.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Mrs..  ',
          displayName: 'Turner, Gusikowski and Cronin',
          billingAddress: '1838 Jairo Union, Boehmport, Macao',
          shippingAddress:
            '1684 Madie Union, Lueilwitzborough, Russian Federation',
          email: 'Ally_Cummerata31@gmail.com',
          phone: '526-233-8932 x52496',
          mobile: '1-232-389-5217 x3238',
          fax: '(247) 304-5150 x9353',
          taxNo: 'TA20181013330',
          otherDetails:
            "Pa'anga primary Garden, Clothing & Tools one-to-one zero defect Shoes Incredible Granite Chair 5th generation TCP circuit",
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174190,
          createdBy: 'Leland Bahringer',
          createdOn: '2018-10-12T13:27:41.5308604+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaV0=',
          userName: null
        },
        {
          code: 'CS20181013331',
          companyName: 'Bode, Marks and Schamberger',
          title: 'Mrs.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Mrs..  ',
          displayName: 'Konopelski, Lehner and Jaskolski',
          billingAddress: '58795 Schamberger Mill, Leuschketown, Niger',
          shippingAddress:
            '350 Aurelie Creek, Pouroshaven, Trinidad and Tobago',
          email: 'Gino.White38@yahoo.com',
          phone: '1-587-480-9850',
          mobile: '663-556-8274 x941',
          fax: '(886) 228-9503 x33228',
          taxNo: 'TA20181013332',
          otherDetails:
            'grey pink whiteboard Games parse Strategist XML invoice Mountains pixel',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174191,
          createdBy: 'Ally Mills',
          createdOn: '2018-10-12T13:27:41.5309288+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaV4=',
          userName: null
        },
        {
          code: 'CS20181013333',
          companyName: 'Satterfield, Altenwerth and Bartell',
          title: 'Ms.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Ms..  ',
          displayName: 'Balistreri, Schultz and Bashirian',
          billingAddress: '692 Ottilie Track, VonRuedenchester, Malta',
          shippingAddress: '2177 Orn Park, Hesselhaven, Yemen',
          email: 'Halie_Abbott67@hotmail.com',
          phone: '936.816.1040',
          mobile: '335.790.9959',
          fax: '487-277-9433 x744',
          taxNo: 'TA20181013334',
          otherDetails:
            'silver synergy Cordoba Oro protocol virtual Investment Account bandwidth California reciprocal Ghana',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174192,
          createdBy: 'Nikolas Jakubowski',
          createdOn: '2018-10-12T13:27:41.5309972+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaV8=',
          userName: null
        },
        {
          code: 'CS20181013335',
          companyName: 'Bailey, Beier and Monahan',
          title: 'Miss',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Miss.  ',
          displayName: "Friesen, Hand and D'Amore",
          billingAddress: '35622 Stanley Hill, Predovicbury, Hong Kong',
          shippingAddress: '7656 Cameron Roads, West Melvina, Albania',
          email: 'Camilla.Gottlieb18@gmail.com',
          phone: '565.993.4665 x58126',
          mobile: '328.563.6036',
          fax: '1-804-663-3470 x100',
          taxNo: 'TA20181013336',
          otherDetails:
            'Zambian Kwacha Handcrafted Wooden Gloves Senior Handcrafted Steel Sausages Incredible Credit Card Account Checking Account Personal Loan Account SCSI Louisiana',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174193,
          createdBy: 'Bo Hessel',
          createdOn: '2018-10-12T13:27:41.5310825+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWA=',
          userName: null
        },
        {
          code: 'CS20181013337',
          companyName: 'Fadel, Huels and Mueller',
          title: 'Ms.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Ms..  ',
          displayName: 'Crist, Reynolds and Williamson',
          billingAddress: '055 Nestor Street, New Myaland, United Kingdom',
          shippingAddress: '85823 Richie Loaf, Harveychester, Senegal',
          email: 'Kayley96@hotmail.com',
          phone: '245-807-2411 x55163',
          mobile: '1-503-441-7141 x735',
          fax: '1-529-216-6378 x797',
          taxNo: 'TA20181013338',
          otherDetails:
            'Saint Helena Pound Cambridgeshire Officer Missouri synthesize Incredible Manager Data parsing Licensed Fresh Chicken',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174194,
          createdBy: 'Lazaro Botsford',
          createdOn: '2018-10-12T13:27:41.531157+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWE=',
          userName: null
        },
        {
          code: 'CS20181013339',
          companyName: 'Streich, Douglas and Upton',
          title: 'Miss',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Miss.  ',
          displayName: 'Kertzmann, Deckow and Bashirian',
          billingAddress: '64161 Presley Center, New Kristian, Swaziland',
          shippingAddress: '133 Shane Alley, Lake Gertrude, Jordan',
          email: 'Muriel.Kautzer@gmail.com',
          phone: '(654) 203-1184 x26287',
          mobile: '(602) 385-7275 x07019',
          fax: '699-868-5186 x011',
          taxNo: 'TA20181013340',
          otherDetails:
            'Tasty Division Buckinghamshire Silver Agent Tasty Fresh Shirt envisioneer Small Internal Expressway',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174195,
          createdBy: 'Edna Gottlieb',
          createdOn: '2018-10-12T13:27:41.5312274+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWI=',
          userName: null
        },
        {
          code: 'CS20181013341',
          companyName: 'Morar, Jast and Green',
          title: 'Mrs.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Mrs..  ',
          displayName: 'Pouros, Koelpin and Jacobi',
          billingAddress: '687 Anika Mountain, Schadenport, Comoros',
          shippingAddress: '586 Cormier Hill, Jarredburgh, Andorra',
          email: 'Wilfrid.Ryan@gmail.com',
          phone: '1-705-845-9412',
          mobile: '548-599-6998',
          fax: '816.848.8674 x180',
          taxNo: 'TA20181013342',
          otherDetails:
            'Intuitive Lead SCSI stable Dynamic interfaces Bedfordshire bi-directional Cambridgeshire parsing',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174196,
          createdBy: 'Sienna Lehner',
          createdOn: '2018-10-12T13:27:41.5312962+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWM=',
          userName: null
        },
        {
          code: 'CS20181013343',
          companyName: 'Brekke, Grimes and Carter',
          title: 'Miss',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Miss.  ',
          displayName: 'Grant, Kub and Rice',
          billingAddress: '9796 Maggio Harbor, Bernardside, Martinique',
          shippingAddress: '8177 Laura Heights, New Gladyceland, Chile',
          email: 'Lance33@hotmail.com',
          phone: '915.915.7832 x086',
          mobile: '1-886-449-2542 x591',
          fax: '511.482.1394',
          taxNo: 'TA20181013344',
          otherDetails:
            'Park 3rd generation copy optical Sports Awesome Fresh Chips Auto Loan Account Usability New Jersey Money Market Account',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174197,
          createdBy: 'Anibal Bednar',
          createdOn: '2018-10-12T13:27:41.5313663+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWQ=',
          userName: null
        },
        {
          code: 'CS20181013345',
          companyName: 'Kautzer, McDermott and Bode',
          title: 'Mr.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Mr..  ',
          displayName: 'Heidenreich, Daugherty and Ullrich',
          billingAddress: '53273 Christelle Stream, East Imaniberg, Iraq',
          shippingAddress: '952 Dietrich Fields, New Bradly, Paraguay',
          email: 'Arnoldo73@hotmail.com',
          phone: '874.771.9411 x7824',
          mobile: '(273) 830-8914',
          fax: '(879) 547-8119',
          taxNo: 'TA20181013346',
          otherDetails:
            'Tennessee AI brand Monitored Incredible Granite Mouse Cotton paradigm withdrawal Fantastic Operations',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174198,
          createdBy: 'Trace Goodwin',
          createdOn: '2018-10-12T13:27:41.5314353+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWU=',
          userName: null
        },
        {
          code: 'CS20181013347',
          companyName: 'Borer, Bednar and Miller',
          title: 'Mrs.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Mrs..  ',
          displayName: "D'Amore, Collier and Walsh",
          billingAddress:
            '105 Kozey Lakes, Eunaborough, Northern Mariana Islands',
          shippingAddress:
            '90951 Adrienne Stravenue, Greenfelderland, Macedonia',
          email: 'Johnny11@yahoo.com',
          phone: '1-241-807-5751 x4598',
          mobile: '466.929.6563 x85387',
          fax: '428-969-7061 x466',
          taxNo: 'TA20181013348',
          otherDetails:
            'Central Azerbaijanian Manat AI Division Money Market Account Global next-generation Steel California Auto Loan Account',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174199,
          createdBy: 'Waino Lindgren',
          createdOn: '2018-10-12T13:27:41.5315054+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWY=',
          userName: null
        },
        {
          code: 'CS20181013349',
          companyName: 'Harris, Ritchie and Schmidt',
          title: 'Mr.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Mr..  ',
          displayName: 'Balistreri, Breitenberg and Romaguera',
          billingAddress: '9753 Mante Turnpike, West Bobbie, Morocco',
          shippingAddress: '63850 Rashad Station, Nienowstad, Poland',
          email: 'Leanna_Brekke5@hotmail.com',
          phone: '1-876-769-7224 x2839',
          mobile: '443-490-5240 x90818',
          fax: '1-481-408-9154 x86786',
          taxNo: 'TA20181013350',
          otherDetails:
            'Oklahoma copy Solutions TCP Cotton British Indian Ocean Territory (Chagos Archipelago) Sleek wireless XML Metal',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174200,
          createdBy: 'Neva West',
          createdOn: '2018-10-12T13:27:41.531579+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWc=',
          userName: null
        },
        {
          code: 'CS20181013351',
          companyName: 'Davis, Erdman and Schneider',
          title: 'Miss',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Miss.  ',
          displayName: 'Stracke, Vandervort and Labadie',
          billingAddress: '42774 Warren Via, Rebeccastad, Rwanda',
          shippingAddress: '96794 Lessie Fords, South Mayefort, Greenland',
          email: 'Alisha_Jerde@gmail.com',
          phone: '1-331-309-4471 x417',
          mobile: '546.725.8522',
          fax: '(859) 346-4359',
          taxNo: 'TA20181013352',
          otherDetails:
            'Fantastic Frozen Table De-engineered Knoll Coordinator relationships withdrawal Communications exuding Arkansas Awesome Metal Gloves',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174201,
          createdBy: 'Juston Keebler',
          createdOn: '2018-10-12T13:27:41.5316485+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWg=',
          userName: null
        },
        {
          code: 'CS20181013353',
          companyName: 'Schulist, Quigley and Hansen',
          title: 'Ms.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Ms..  ',
          displayName: 'Schaden, Lockman and Blanda',
          billingAddress: '24208 Eve Turnpike, North Rossie, Jordan',
          shippingAddress: '8906 Ondricka Valley, West Kyle, South Africa',
          email: 'Monica.Waelchi62@gmail.com',
          phone: '495-991-0923 x502',
          mobile: '1-362-329-5033',
          fax: '(454) 770-3310',
          taxNo: 'TA20181013354',
          otherDetails:
            'back-end Refined Frozen Salad Corporate content-based Auto Loan Account Group withdrawal middleware West Virginia deposit',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174202,
          createdBy: 'Haven Donnelly',
          createdOn: '2018-10-12T13:27:41.531722+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWk=',
          userName: null
        },
        {
          code: 'CS20181013355',
          companyName: 'Hermann, Brown and Volkman',
          title: 'Mrs.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Mrs..  ',
          displayName: 'Bergnaum, Nicolas and Morar',
          billingAddress:
            '0457 Hermann Stream, Lake Gregoriachester, Papua New Guinea',
          shippingAddress: '90782 Marquise Rue, Sydneyland, Paraguay',
          email: 'Tremayne_Rutherford16@hotmail.com',
          phone: '749.482.6406',
          mobile: '283-715-1422',
          fax: '291.235.2898 x747',
          taxNo: 'TA20181013356',
          otherDetails:
            'metrics Music & Kids panel harness Programmable Stand-alone monetize next generation Investment Account Parkway',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174203,
          createdBy: 'Paxton Keebler',
          createdOn: '2018-10-12T13:27:41.5317908+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWo=',
          userName: null
        },
        {
          code: 'CS20181013325',
          companyName: 'Kautzer, Halvorson and Jakubowski',
          title: 'Ms.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Ms..  ',
          displayName: "O'Keefe, Parker and Gorczany",
          billingAddress: '52558 Judge Roads, New Paige, Macedonia',
          shippingAddress: '133 Ambrose Dam, Jordanechester, Cape Verde',
          email: 'Rahsaan64@yahoo.com',
          phone: '610.749.3527',
          mobile: '494-355-0849 x9720',
          fax: '1-305-498-5984 x648',
          taxNo: 'TA20181013326',
          otherDetails:
            'Soft Malagasy Ariary Senior throughput Tasty reboot synergistic payment Orchestrator payment',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174204,
          createdBy: 'Angelita Johns',
          createdOn: '2018-10-12T13:27:41.5307217+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWs=',
          userName: null
        },
        {
          code: 'CS20181013323',
          companyName: 'Hoeger, Mraz and Terry',
          title: 'Dr.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Dr..  ',
          displayName: 'Koss, Bins and Beahan',
          billingAddress: '0330 Schimmel Crest, West Jannieview, Montenegro',
          shippingAddress: '5215 Dicki Gateway, Hellerfurt, France',
          email: 'Jalyn.Heidenreich38@gmail.com',
          phone: '1-790-626-9168',
          mobile: '264-511-0531 x72869',
          fax: '1-874-247-5255',
          taxNo: 'TA20181013324',
          otherDetails:
            'Tactics leverage Rustic content Handcrafted Rubber Ball black synthesize logistical convergence Buckinghamshire',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174205,
          createdBy: 'Dasia Williamson',
          createdOn: '2018-10-12T13:27:41.5306513+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWw=',
          userName: null
        },
        {
          code: 'CS20181013321',
          companyName: 'Kuhic, Marquardt and Jacobi',
          title: 'Mrs.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Mrs..  ',
          displayName: 'Tillman, Bartell and Cartwright',
          billingAddress: '7576 Genevieve Roads, New Hattieburgh, Mayotte',
          shippingAddress: '594 Weber Valleys, North Emmanuelle, Bermuda',
          email: 'Larry54@gmail.com',
          phone: '(468) 394-5160',
          mobile: '561-906-6102 x26859',
          fax: '719.306.9180 x957',
          taxNo: 'TA20181013322',
          otherDetails:
            'Investment Account Awesome port Small Coordinator Clothing, Home & Outdoors Administrator Missouri Movies Human',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174206,
          createdBy: 'Eleonore Dooley',
          createdOn: '2018-10-12T13:27:41.5305826+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaW0=',
          userName: null
        },
        {
          code: 'CS20181013319',
          companyName: 'Block, Little and Dach',
          title: 'Ms.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Ms..  ',
          displayName: 'Prohaska, Lubowitz and Mraz',
          billingAddress: '993 Elwin Valleys, Wymanfurt, Brazil',
          shippingAddress: '6812 Quinn Points, South Lynnmouth, Oman',
          email: 'Orland.Hilll71@hotmail.com',
          phone: '482-767-9481 x8117',
          mobile: '653.736.5811',
          fax: '1-214-577-2536 x26346',
          taxNo: 'TA20181013320',
          otherDetails:
            'Estate deposit one-to-one utilisation enterprise protocol overriding generate systems incubate',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174207,
          createdBy: 'Astrid Pollich',
          createdOn: '2018-10-12T13:27:41.530513+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaW4=',
          userName: null
        }
      ]
    };

    const result = mergeData(original, latest);

    expect(result).toMatchObject(latest);
  });

  test('merge object with array prop original NULL', () => {
    const original = undefined;

    const latest = {
      includeArchived: false,
      searchText: null,
      orderBy: null,
      direction: 'Asc',
      pageIndex: 0,
      pageSize: 20,
      totalItems: 9992,
      totalPage: 500,
      items: [
        {
          code: 'CSYY100001',
          companyName: 'chdhfjfjgfgjfj',
          title: null,
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: '.  ',
          displayName: 'tdrydrydrydr',
          billingAddress: null,
          shippingAddress: null,
          email: null,
          phone: null,
          mobile: null,
          fax: null,
          taxNo: null,
          otherDetails: null,
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 1,
          createdBy: 'Tuan',
          createdOn: '2018-10-12T03:34:54.2364397+00:00',
          updatedBy: 'Tuan',
          updatedOn: '2018-10-12T03:35:20.8541415+00:00',
          isDeleted: false,
          rowVersion: 'AAAAAAADG1U=',
          userName: null
        },
        {
          code: 'CS20181013327',
          companyName: 'Dibbert, Funk and Cremin',
          title: 'Miss',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Miss.  ',
          displayName: 'Strosin, Wuckert and Deckow',
          billingAddress: '45022 Muller Extension, Lucianoton, Togo',
          shippingAddress: '879 Yundt Springs, Nitzscheside, Tokelau',
          email: 'Wilburn88@hotmail.com',
          phone: '543.345.2302 x02094',
          mobile: '1-708-960-8951',
          fax: '1-322-862-3812 x406',
          taxNo: 'TA20181013328',
          otherDetails:
            'zero administration invoice connecting Heights interactive content Squares bluetooth invoice back-end',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174189,
          createdBy: "Jodie O'Connell",
          createdOn: '2018-10-12T13:27:41.5307907+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaVw=',
          userName: null
        },
        {
          code: 'CS20181013329',
          companyName: 'Stanton, Monahan and Gorczany',
          title: 'Mrs.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Mrs..  ',
          displayName: 'Turner, Gusikowski and Cronin',
          billingAddress: '1838 Jairo Union, Boehmport, Macao',
          shippingAddress:
            '1684 Madie Union, Lueilwitzborough, Russian Federation',
          email: 'Ally_Cummerata31@gmail.com',
          phone: '526-233-8932 x52496',
          mobile: '1-232-389-5217 x3238',
          fax: '(247) 304-5150 x9353',
          taxNo: 'TA20181013330',
          otherDetails:
            "Pa'anga primary Garden, Clothing & Tools one-to-one zero defect Shoes Incredible Granite Chair 5th generation TCP circuit",
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174190,
          createdBy: 'Leland Bahringer',
          createdOn: '2018-10-12T13:27:41.5308604+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaV0=',
          userName: null
        },
        {
          code: 'CS20181013331',
          companyName: 'Bode, Marks and Schamberger',
          title: 'Mrs.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Mrs..  ',
          displayName: 'Konopelski, Lehner and Jaskolski',
          billingAddress: '58795 Schamberger Mill, Leuschketown, Niger',
          shippingAddress:
            '350 Aurelie Creek, Pouroshaven, Trinidad and Tobago',
          email: 'Gino.White38@yahoo.com',
          phone: '1-587-480-9850',
          mobile: '663-556-8274 x941',
          fax: '(886) 228-9503 x33228',
          taxNo: 'TA20181013332',
          otherDetails:
            'grey pink whiteboard Games parse Strategist XML invoice Mountains pixel',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174191,
          createdBy: 'Ally Mills',
          createdOn: '2018-10-12T13:27:41.5309288+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaV4=',
          userName: null
        },
        {
          code: 'CS20181013333',
          companyName: 'Satterfield, Altenwerth and Bartell',
          title: 'Ms.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Ms..  ',
          displayName: 'Balistreri, Schultz and Bashirian',
          billingAddress: '692 Ottilie Track, VonRuedenchester, Malta',
          shippingAddress: '2177 Orn Park, Hesselhaven, Yemen',
          email: 'Halie_Abbott67@hotmail.com',
          phone: '936.816.1040',
          mobile: '335.790.9959',
          fax: '487-277-9433 x744',
          taxNo: 'TA20181013334',
          otherDetails:
            'silver synergy Cordoba Oro protocol virtual Investment Account bandwidth California reciprocal Ghana',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174192,
          createdBy: 'Nikolas Jakubowski',
          createdOn: '2018-10-12T13:27:41.5309972+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaV8=',
          userName: null
        },
        {
          code: 'CS20181013335',
          companyName: 'Bailey, Beier and Monahan',
          title: 'Miss',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Miss.  ',
          displayName: "Friesen, Hand and D'Amore",
          billingAddress: '35622 Stanley Hill, Predovicbury, Hong Kong',
          shippingAddress: '7656 Cameron Roads, West Melvina, Albania',
          email: 'Camilla.Gottlieb18@gmail.com',
          phone: '565.993.4665 x58126',
          mobile: '328.563.6036',
          fax: '1-804-663-3470 x100',
          taxNo: 'TA20181013336',
          otherDetails:
            'Zambian Kwacha Handcrafted Wooden Gloves Senior Handcrafted Steel Sausages Incredible Credit Card Account Checking Account Personal Loan Account SCSI Louisiana',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174193,
          createdBy: 'Bo Hessel',
          createdOn: '2018-10-12T13:27:41.5310825+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWA=',
          userName: null
        },
        {
          code: 'CS20181013337',
          companyName: 'Fadel, Huels and Mueller',
          title: 'Ms.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Ms..  ',
          displayName: 'Crist, Reynolds and Williamson',
          billingAddress: '055 Nestor Street, New Myaland, United Kingdom',
          shippingAddress: '85823 Richie Loaf, Harveychester, Senegal',
          email: 'Kayley96@hotmail.com',
          phone: '245-807-2411 x55163',
          mobile: '1-503-441-7141 x735',
          fax: '1-529-216-6378 x797',
          taxNo: 'TA20181013338',
          otherDetails:
            'Saint Helena Pound Cambridgeshire Officer Missouri synthesize Incredible Manager Data parsing Licensed Fresh Chicken',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174194,
          createdBy: 'Lazaro Botsford',
          createdOn: '2018-10-12T13:27:41.531157+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWE=',
          userName: null
        },
        {
          code: 'CS20181013339',
          companyName: 'Streich, Douglas and Upton',
          title: 'Miss',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Miss.  ',
          displayName: 'Kertzmann, Deckow and Bashirian',
          billingAddress: '64161 Presley Center, New Kristian, Swaziland',
          shippingAddress: '133 Shane Alley, Lake Gertrude, Jordan',
          email: 'Muriel.Kautzer@gmail.com',
          phone: '(654) 203-1184 x26287',
          mobile: '(602) 385-7275 x07019',
          fax: '699-868-5186 x011',
          taxNo: 'TA20181013340',
          otherDetails:
            'Tasty Division Buckinghamshire Silver Agent Tasty Fresh Shirt envisioneer Small Internal Expressway',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174195,
          createdBy: 'Edna Gottlieb',
          createdOn: '2018-10-12T13:27:41.5312274+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWI=',
          userName: null
        },
        {
          code: 'CS20181013341',
          companyName: 'Morar, Jast and Green',
          title: 'Mrs.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Mrs..  ',
          displayName: 'Pouros, Koelpin and Jacobi',
          billingAddress: '687 Anika Mountain, Schadenport, Comoros',
          shippingAddress: '586 Cormier Hill, Jarredburgh, Andorra',
          email: 'Wilfrid.Ryan@gmail.com',
          phone: '1-705-845-9412',
          mobile: '548-599-6998',
          fax: '816.848.8674 x180',
          taxNo: 'TA20181013342',
          otherDetails:
            'Intuitive Lead SCSI stable Dynamic interfaces Bedfordshire bi-directional Cambridgeshire parsing',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174196,
          createdBy: 'Sienna Lehner',
          createdOn: '2018-10-12T13:27:41.5312962+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWM=',
          userName: null
        },
        {
          code: 'CS20181013343',
          companyName: 'Brekke, Grimes and Carter',
          title: 'Miss',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Miss.  ',
          displayName: 'Grant, Kub and Rice',
          billingAddress: '9796 Maggio Harbor, Bernardside, Martinique',
          shippingAddress: '8177 Laura Heights, New Gladyceland, Chile',
          email: 'Lance33@hotmail.com',
          phone: '915.915.7832 x086',
          mobile: '1-886-449-2542 x591',
          fax: '511.482.1394',
          taxNo: 'TA20181013344',
          otherDetails:
            'Park 3rd generation copy optical Sports Awesome Fresh Chips Auto Loan Account Usability New Jersey Money Market Account',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174197,
          createdBy: 'Anibal Bednar',
          createdOn: '2018-10-12T13:27:41.5313663+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWQ=',
          userName: null
        },
        {
          code: 'CS20181013345',
          companyName: 'Kautzer, McDermott and Bode',
          title: 'Mr.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Mr..  ',
          displayName: 'Heidenreich, Daugherty and Ullrich',
          billingAddress: '53273 Christelle Stream, East Imaniberg, Iraq',
          shippingAddress: '952 Dietrich Fields, New Bradly, Paraguay',
          email: 'Arnoldo73@hotmail.com',
          phone: '874.771.9411 x7824',
          mobile: '(273) 830-8914',
          fax: '(879) 547-8119',
          taxNo: 'TA20181013346',
          otherDetails:
            'Tennessee AI brand Monitored Incredible Granite Mouse Cotton paradigm withdrawal Fantastic Operations',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174198,
          createdBy: 'Trace Goodwin',
          createdOn: '2018-10-12T13:27:41.5314353+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWU=',
          userName: null
        },
        {
          code: 'CS20181013347',
          companyName: 'Borer, Bednar and Miller',
          title: 'Mrs.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Mrs..  ',
          displayName: "D'Amore, Collier and Walsh",
          billingAddress:
            '105 Kozey Lakes, Eunaborough, Northern Mariana Islands',
          shippingAddress:
            '90951 Adrienne Stravenue, Greenfelderland, Macedonia',
          email: 'Johnny11@yahoo.com',
          phone: '1-241-807-5751 x4598',
          mobile: '466.929.6563 x85387',
          fax: '428-969-7061 x466',
          taxNo: 'TA20181013348',
          otherDetails:
            'Central Azerbaijanian Manat AI Division Money Market Account Global next-generation Steel California Auto Loan Account',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174199,
          createdBy: 'Waino Lindgren',
          createdOn: '2018-10-12T13:27:41.5315054+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWY=',
          userName: null
        },
        {
          code: 'CS20181013349',
          companyName: 'Harris, Ritchie and Schmidt',
          title: 'Mr.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Mr..  ',
          displayName: 'Balistreri, Breitenberg and Romaguera',
          billingAddress: '9753 Mante Turnpike, West Bobbie, Morocco',
          shippingAddress: '63850 Rashad Station, Nienowstad, Poland',
          email: 'Leanna_Brekke5@hotmail.com',
          phone: '1-876-769-7224 x2839',
          mobile: '443-490-5240 x90818',
          fax: '1-481-408-9154 x86786',
          taxNo: 'TA20181013350',
          otherDetails:
            'Oklahoma copy Solutions TCP Cotton British Indian Ocean Territory (Chagos Archipelago) Sleek wireless XML Metal',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174200,
          createdBy: 'Neva West',
          createdOn: '2018-10-12T13:27:41.531579+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWc=',
          userName: null
        },
        {
          code: 'CS20181013351',
          companyName: 'Davis, Erdman and Schneider',
          title: 'Miss',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Miss.  ',
          displayName: 'Stracke, Vandervort and Labadie',
          billingAddress: '42774 Warren Via, Rebeccastad, Rwanda',
          shippingAddress: '96794 Lessie Fords, South Mayefort, Greenland',
          email: 'Alisha_Jerde@gmail.com',
          phone: '1-331-309-4471 x417',
          mobile: '546.725.8522',
          fax: '(859) 346-4359',
          taxNo: 'TA20181013352',
          otherDetails:
            'Fantastic Frozen Table De-engineered Knoll Coordinator relationships withdrawal Communications exuding Arkansas Awesome Metal Gloves',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174201,
          createdBy: 'Juston Keebler',
          createdOn: '2018-10-12T13:27:41.5316485+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWg=',
          userName: null
        },
        {
          code: 'CS20181013353',
          companyName: 'Schulist, Quigley and Hansen',
          title: 'Ms.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Ms..  ',
          displayName: 'Schaden, Lockman and Blanda',
          billingAddress: '24208 Eve Turnpike, North Rossie, Jordan',
          shippingAddress: '8906 Ondricka Valley, West Kyle, South Africa',
          email: 'Monica.Waelchi62@gmail.com',
          phone: '495-991-0923 x502',
          mobile: '1-362-329-5033',
          fax: '(454) 770-3310',
          taxNo: 'TA20181013354',
          otherDetails:
            'back-end Refined Frozen Salad Corporate content-based Auto Loan Account Group withdrawal middleware West Virginia deposit',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174202,
          createdBy: 'Haven Donnelly',
          createdOn: '2018-10-12T13:27:41.531722+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWk=',
          userName: null
        },
        {
          code: 'CS20181013355',
          companyName: 'Hermann, Brown and Volkman',
          title: 'Mrs.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Mrs..  ',
          displayName: 'Bergnaum, Nicolas and Morar',
          billingAddress:
            '0457 Hermann Stream, Lake Gregoriachester, Papua New Guinea',
          shippingAddress: '90782 Marquise Rue, Sydneyland, Paraguay',
          email: 'Tremayne_Rutherford16@hotmail.com',
          phone: '749.482.6406',
          mobile: '283-715-1422',
          fax: '291.235.2898 x747',
          taxNo: 'TA20181013356',
          otherDetails:
            'metrics Music & Kids panel harness Programmable Stand-alone monetize next generation Investment Account Parkway',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174203,
          createdBy: 'Paxton Keebler',
          createdOn: '2018-10-12T13:27:41.5317908+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWo=',
          userName: null
        },
        {
          code: 'CS20181013325',
          companyName: 'Kautzer, Halvorson and Jakubowski',
          title: 'Ms.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Ms..  ',
          displayName: "O'Keefe, Parker and Gorczany",
          billingAddress: '52558 Judge Roads, New Paige, Macedonia',
          shippingAddress: '133 Ambrose Dam, Jordanechester, Cape Verde',
          email: 'Rahsaan64@yahoo.com',
          phone: '610.749.3527',
          mobile: '494-355-0849 x9720',
          fax: '1-305-498-5984 x648',
          taxNo: 'TA20181013326',
          otherDetails:
            'Soft Malagasy Ariary Senior throughput Tasty reboot synergistic payment Orchestrator payment',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174204,
          createdBy: 'Angelita Johns',
          createdOn: '2018-10-12T13:27:41.5307217+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWs=',
          userName: null
        },
        {
          code: 'CS20181013323',
          companyName: 'Hoeger, Mraz and Terry',
          title: 'Dr.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Dr..  ',
          displayName: 'Koss, Bins and Beahan',
          billingAddress: '0330 Schimmel Crest, West Jannieview, Montenegro',
          shippingAddress: '5215 Dicki Gateway, Hellerfurt, France',
          email: 'Jalyn.Heidenreich38@gmail.com',
          phone: '1-790-626-9168',
          mobile: '264-511-0531 x72869',
          fax: '1-874-247-5255',
          taxNo: 'TA20181013324',
          otherDetails:
            'Tactics leverage Rustic content Handcrafted Rubber Ball black synthesize logistical convergence Buckinghamshire',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174205,
          createdBy: 'Dasia Williamson',
          createdOn: '2018-10-12T13:27:41.5306513+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWw=',
          userName: null
        },
        {
          code: 'CS20181013321',
          companyName: 'Kuhic, Marquardt and Jacobi',
          title: 'Mrs.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Mrs..  ',
          displayName: 'Tillman, Bartell and Cartwright',
          billingAddress: '7576 Genevieve Roads, New Hattieburgh, Mayotte',
          shippingAddress: '594 Weber Valleys, North Emmanuelle, Bermuda',
          email: 'Larry54@gmail.com',
          phone: '(468) 394-5160',
          mobile: '561-906-6102 x26859',
          fax: '719.306.9180 x957',
          taxNo: 'TA20181013322',
          otherDetails:
            'Investment Account Awesome port Small Coordinator Clothing, Home & Outdoors Administrator Missouri Movies Human',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174206,
          createdBy: 'Eleonore Dooley',
          createdOn: '2018-10-12T13:27:41.5305826+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaW0=',
          userName: null
        },
        {
          code: 'CS20181013319',
          companyName: 'Block, Little and Dach',
          title: 'Ms.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Ms..  ',
          displayName: 'Prohaska, Lubowitz and Mraz',
          billingAddress: '993 Elwin Valleys, Wymanfurt, Brazil',
          shippingAddress: '6812 Quinn Points, South Lynnmouth, Oman',
          email: 'Orland.Hilll71@hotmail.com',
          phone: '482-767-9481 x8117',
          mobile: '653.736.5811',
          fax: '1-214-577-2536 x26346',
          taxNo: 'TA20181013320',
          otherDetails:
            'Estate deposit one-to-one utilisation enterprise protocol overriding generate systems incubate',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174207,
          createdBy: 'Astrid Pollich',
          createdOn: '2018-10-12T13:27:41.530513+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaW4=',
          userName: null
        }
      ]
    };

    const result = mergeData(original, latest);

    expect(result).toMatchObject(latest);
  });

  test('merge object with array prop latest Empty', () => {
    const original = {
      includeArchived: false,
      searchText: null,
      orderBy: null,
      direction: 'Asc',
      pageIndex: 0,
      pageSize: 10,
      totalItems: 9992,
      totalPage: 1000,
      items: [
        {
          code: 'CSYY100001',
          companyName: 'chdhfjfjgfgjfj',
          title: null,
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: '.  ',
          displayName: 'tdrydrydrydr',
          billingAddress: null,
          shippingAddress: null,
          email: null,
          phone: null,
          mobile: null,
          fax: null,
          taxNo: null,
          otherDetails: null,
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 1,
          createdBy: 'Tuan',
          createdOn: '2018-10-12T03:34:54.2364397+00:00',
          updatedBy: 'Tuan',
          updatedOn: '2018-10-12T03:35:20.8541415+00:00',
          isDeleted: false,
          rowVersion: 'AAAAAAADG1U=',
          userName: null
        },
        {
          code: 'CS20181013327',
          companyName: 'Dibbert, Funk and Cremin',
          title: 'Miss',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Miss.  ',
          displayName: 'Strosin, Wuckert and Deckow',
          billingAddress: '45022 Muller Extension, Lucianoton, Togo',
          shippingAddress: '879 Yundt Springs, Nitzscheside, Tokelau',
          email: 'Wilburn88@hotmail.com',
          phone: '543.345.2302 x02094',
          mobile: '1-708-960-8951',
          fax: '1-322-862-3812 x406',
          taxNo: 'TA20181013328',
          otherDetails:
            'zero administration invoice connecting Heights interactive content Squares bluetooth invoice back-end',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174189,
          createdBy: "Jodie O'Connell",
          createdOn: '2018-10-12T13:27:41.5307907+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaVw=',
          userName: null
        },
        {
          code: 'CS20181013329',
          companyName: 'Stanton, Monahan and Gorczany',
          title: 'Mrs.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Mrs..  ',
          displayName: 'Turner, Gusikowski and Cronin',
          billingAddress: '1838 Jairo Union, Boehmport, Macao',
          shippingAddress:
            '1684 Madie Union, Lueilwitzborough, Russian Federation',
          email: 'Ally_Cummerata31@gmail.com',
          phone: '526-233-8932 x52496',
          mobile: '1-232-389-5217 x3238',
          fax: '(247) 304-5150 x9353',
          taxNo: 'TA20181013330',
          otherDetails:
            "Pa'anga primary Garden, Clothing & Tools one-to-one zero defect Shoes Incredible Granite Chair 5th generation TCP circuit",
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174190,
          createdBy: 'Leland Bahringer',
          createdOn: '2018-10-12T13:27:41.5308604+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaV0=',
          userName: null
        },
        {
          code: 'CS20181013331',
          companyName: 'Bode, Marks and Schamberger',
          title: 'Mrs.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Mrs..  ',
          displayName: 'Konopelski, Lehner and Jaskolski',
          billingAddress: '58795 Schamberger Mill, Leuschketown, Niger',
          shippingAddress:
            '350 Aurelie Creek, Pouroshaven, Trinidad and Tobago',
          email: 'Gino.White38@yahoo.com',
          phone: '1-587-480-9850',
          mobile: '663-556-8274 x941',
          fax: '(886) 228-9503 x33228',
          taxNo: 'TA20181013332',
          otherDetails:
            'grey pink whiteboard Games parse Strategist XML invoice Mountains pixel',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174191,
          createdBy: 'Ally Mills',
          createdOn: '2018-10-12T13:27:41.5309288+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaV4=',
          userName: null
        },
        {
          code: 'CS20181013333',
          companyName: 'Satterfield, Altenwerth and Bartell',
          title: 'Ms.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Ms..  ',
          displayName: 'Balistreri, Schultz and Bashirian',
          billingAddress: '692 Ottilie Track, VonRuedenchester, Malta',
          shippingAddress: '2177 Orn Park, Hesselhaven, Yemen',
          email: 'Halie_Abbott67@hotmail.com',
          phone: '936.816.1040',
          mobile: '335.790.9959',
          fax: '487-277-9433 x744',
          taxNo: 'TA20181013334',
          otherDetails:
            'silver synergy Cordoba Oro protocol virtual Investment Account bandwidth California reciprocal Ghana',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174192,
          createdBy: 'Nikolas Jakubowski',
          createdOn: '2018-10-12T13:27:41.5309972+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaV8=',
          userName: null
        },
        {
          code: 'CS20181013335',
          companyName: 'Bailey, Beier and Monahan',
          title: 'Miss',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Miss.  ',
          displayName: "Friesen, Hand and D'Amore",
          billingAddress: '35622 Stanley Hill, Predovicbury, Hong Kong',
          shippingAddress: '7656 Cameron Roads, West Melvina, Albania',
          email: 'Camilla.Gottlieb18@gmail.com',
          phone: '565.993.4665 x58126',
          mobile: '328.563.6036',
          fax: '1-804-663-3470 x100',
          taxNo: 'TA20181013336',
          otherDetails:
            'Zambian Kwacha Handcrafted Wooden Gloves Senior Handcrafted Steel Sausages Incredible Credit Card Account Checking Account Personal Loan Account SCSI Louisiana',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174193,
          createdBy: 'Bo Hessel',
          createdOn: '2018-10-12T13:27:41.5310825+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWA=',
          userName: null
        },
        {
          code: 'CS20181013337',
          companyName: 'Fadel, Huels and Mueller',
          title: 'Ms.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Ms..  ',
          displayName: 'Crist, Reynolds and Williamson',
          billingAddress: '055 Nestor Street, New Myaland, United Kingdom',
          shippingAddress: '85823 Richie Loaf, Harveychester, Senegal',
          email: 'Kayley96@hotmail.com',
          phone: '245-807-2411 x55163',
          mobile: '1-503-441-7141 x735',
          fax: '1-529-216-6378 x797',
          taxNo: 'TA20181013338',
          otherDetails:
            'Saint Helena Pound Cambridgeshire Officer Missouri synthesize Incredible Manager Data parsing Licensed Fresh Chicken',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174194,
          createdBy: 'Lazaro Botsford',
          createdOn: '2018-10-12T13:27:41.531157+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWE=',
          userName: null
        },
        {
          code: 'CS20181013339',
          companyName: 'Streich, Douglas and Upton',
          title: 'Miss',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Miss.  ',
          displayName: 'Kertzmann, Deckow and Bashirian',
          billingAddress: '64161 Presley Center, New Kristian, Swaziland',
          shippingAddress: '133 Shane Alley, Lake Gertrude, Jordan',
          email: 'Muriel.Kautzer@gmail.com',
          phone: '(654) 203-1184 x26287',
          mobile: '(602) 385-7275 x07019',
          fax: '699-868-5186 x011',
          taxNo: 'TA20181013340',
          otherDetails:
            'Tasty Division Buckinghamshire Silver Agent Tasty Fresh Shirt envisioneer Small Internal Expressway',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174195,
          createdBy: 'Edna Gottlieb',
          createdOn: '2018-10-12T13:27:41.5312274+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWI=',
          userName: null
        },
        {
          code: 'CS20181013341',
          companyName: 'Morar, Jast and Green',
          title: 'Mrs.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Mrs..  ',
          displayName: 'Pouros, Koelpin and Jacobi',
          billingAddress: '687 Anika Mountain, Schadenport, Comoros',
          shippingAddress: '586 Cormier Hill, Jarredburgh, Andorra',
          email: 'Wilfrid.Ryan@gmail.com',
          phone: '1-705-845-9412',
          mobile: '548-599-6998',
          fax: '816.848.8674 x180',
          taxNo: 'TA20181013342',
          otherDetails:
            'Intuitive Lead SCSI stable Dynamic interfaces Bedfordshire bi-directional Cambridgeshire parsing',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174196,
          createdBy: 'Sienna Lehner',
          createdOn: '2018-10-12T13:27:41.5312962+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWM=',
          userName: null
        },
        {
          code: 'CS20181013343',
          companyName: 'Brekke, Grimes and Carter',
          title: 'Miss',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Miss.  ',
          displayName: 'Grant, Kub and Rice',
          billingAddress: '9796 Maggio Harbor, Bernardside, Martinique',
          shippingAddress: '8177 Laura Heights, New Gladyceland, Chile',
          email: 'Lance33@hotmail.com',
          phone: '915.915.7832 x086',
          mobile: '1-886-449-2542 x591',
          fax: '511.482.1394',
          taxNo: 'TA20181013344',
          otherDetails:
            'Park 3rd generation copy optical Sports Awesome Fresh Chips Auto Loan Account Usability New Jersey Money Market Account',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174197,
          createdBy: 'Anibal Bednar',
          createdOn: '2018-10-12T13:27:41.5313663+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWQ=',
          userName: null
        }
      ]
    };

    const latest: any = {};

    const result = mergeData(original, latest);

    expect(result).toMatchObject(original);
  });

  test('merge object with array prop with difference position', () => {
    const original = {
      includeArchived: false,
      searchText: null,
      orderBy: null,
      direction: 'Asc',
      pageIndex: 10,
      pageSize: 10,
      totalItems: 9992,
      totalPage: 1000,
      items: [
        {
          code: 'CSYY100001',
          companyName: 'chdhfjfjgfgjfj',
          title: null,
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: '.  ',
          displayName: 'tdrydrydrydr',
          billingAddress: null,
          shippingAddress: null,
          email: null,
          phone: null,
          mobile: null,
          fax: null,
          taxNo: null,
          otherDetails: null,
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 1,
          createdBy: 'Tuan',
          createdOn: '2018-10-12T03:34:54.2364397+00:00',
          updatedBy: 'Tuan',
          updatedOn: '2018-10-12T03:35:20.8541415+00:00',
          isDeleted: false,
          rowVersion: 'AAAAAAADG1U=',
          userName: null
        },
        {
          code: 'CS20181013327',
          companyName: 'Dibbert, Funk and Cremin',
          title: 'Miss',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Miss.  ',
          displayName: 'Strosin, Wuckert and Deckow',
          billingAddress: '45022 Muller Extension, Lucianoton, Togo',
          shippingAddress: '879 Yundt Springs, Nitzscheside, Tokelau',
          email: 'Wilburn88@hotmail.com',
          phone: '543.345.2302 x02094',
          mobile: '1-708-960-8951',
          fax: '1-322-862-3812 x406',
          taxNo: 'TA20181013328',
          otherDetails:
            'zero administration invoice connecting Heights interactive content Squares bluetooth invoice back-end',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174189,
          createdBy: "Jodie O'Connell",
          createdOn: '2018-10-12T13:27:41.5307907+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaVw=',
          userName: null
        }
      ]
    };

    const latest = {
      includeArchived: false,
      searchText: null,
      orderBy: null,
      direction: 'Asc',
      pageIndex: 1,
      pageSize: 20,
      totalItems: 9992,
      totalPage: 500,
      items: [
        {
          code: 'CS20181013337',
          companyName: 'Fadel, Huels and Mueller',
          title: 'Ms.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Ms..  ',
          displayName: 'Crist, Reynolds and Williamson',
          billingAddress: '055 Nestor Street, New Myaland, United Kingdom',
          shippingAddress: '85823 Richie Loaf, Harveychester, Senegal',
          email: 'Kayley96@hotmail.com',
          phone: '245-807-2411 x55163',
          mobile: '1-503-441-7141 x735',
          fax: '1-529-216-6378 x797',
          taxNo: 'TA20181013338',
          otherDetails:
            'Saint Helena Pound Cambridgeshire Officer Missouri synthesize Incredible Manager Data parsing Licensed Fresh Chicken',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174194,
          createdBy: 'Lazaro Botsford',
          createdOn: '2018-10-12T13:27:41.531157+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWE=',
          userName: null
        },
        {
          code: 'CS20181013339',
          companyName: 'Streich, Douglas and Upton',
          title: 'Miss',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Miss.  ',
          displayName: 'Kertzmann, Deckow and Bashirian',
          billingAddress: '64161 Presley Center, New Kristian, Swaziland',
          shippingAddress: '133 Shane Alley, Lake Gertrude, Jordan',
          email: 'Muriel.Kautzer@gmail.com',
          phone: '(654) 203-1184 x26287',
          mobile: '(602) 385-7275 x07019',
          fax: '699-868-5186 x011',
          taxNo: 'TA20181013340',
          otherDetails:
            'Tasty Division Buckinghamshire Silver Agent Tasty Fresh Shirt envisioneer Small Internal Expressway',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174195,
          createdBy: 'Edna Gottlieb',
          createdOn: '2018-10-12T13:27:41.5312274+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWI=',
          userName: null
        },
        {
          code: 'CS20181013341',
          companyName: 'Morar, Jast and Green',
          title: 'Mrs.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Mrs..  ',
          displayName: 'Pouros, Koelpin and Jacobi',
          billingAddress: '687 Anika Mountain, Schadenport, Comoros',
          shippingAddress: '586 Cormier Hill, Jarredburgh, Andorra',
          email: 'Wilfrid.Ryan@gmail.com',
          phone: '1-705-845-9412',
          mobile: '548-599-6998',
          fax: '816.848.8674 x180',
          taxNo: 'TA20181013342',
          otherDetails:
            'Intuitive Lead SCSI stable Dynamic interfaces Bedfordshire bi-directional Cambridgeshire parsing',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174196,
          createdBy: 'Sienna Lehner',
          createdOn: '2018-10-12T13:27:41.5312962+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWM=',
          userName: null
        },
        {
          code: 'CS20181013343',
          companyName: 'Brekke, Grimes and Carter',
          title: 'Miss',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Miss.  ',
          displayName: 'Grant, Kub and Rice',
          billingAddress: '9796 Maggio Harbor, Bernardside, Martinique',
          shippingAddress: '8177 Laura Heights, New Gladyceland, Chile',
          email: 'Lance33@hotmail.com',
          phone: '915.915.7832 x086',
          mobile: '1-886-449-2542 x591',
          fax: '511.482.1394',
          taxNo: 'TA20181013344',
          otherDetails:
            'Park 3rd generation copy optical Sports Awesome Fresh Chips Auto Loan Account Usability New Jersey Money Market Account',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174197,
          createdBy: 'Anibal Bednar',
          createdOn: '2018-10-12T13:27:41.5313663+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWQ=',
          userName: null
        },
        {
          code: 'CS20181013345',
          companyName: 'Kautzer, McDermott and Bode',
          title: 'Mr.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Mr..  ',
          displayName: 'Heidenreich, Daugherty and Ullrich',
          billingAddress: '53273 Christelle Stream, East Imaniberg, Iraq',
          shippingAddress: '952 Dietrich Fields, New Bradly, Paraguay',
          email: 'Arnoldo73@hotmail.com',
          phone: '874.771.9411 x7824',
          mobile: '(273) 830-8914',
          fax: '(879) 547-8119',
          taxNo: 'TA20181013346',
          otherDetails:
            'Tennessee AI brand Monitored Incredible Granite Mouse Cotton paradigm withdrawal Fantastic Operations',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174198,
          createdBy: 'Trace Goodwin',
          createdOn: '2018-10-12T13:27:41.5314353+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWU=',
          userName: null
        },
        {
          code: 'CS20181013347',
          companyName: 'Borer, Bednar and Miller',
          title: 'Mrs.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Mrs..  ',
          displayName: "D'Amore, Collier and Walsh",
          billingAddress:
            '105 Kozey Lakes, Eunaborough, Northern Mariana Islands',
          shippingAddress:
            '90951 Adrienne Stravenue, Greenfelderland, Macedonia',
          email: 'Johnny11@yahoo.com',
          phone: '1-241-807-5751 x4598',
          mobile: '466.929.6563 x85387',
          fax: '428-969-7061 x466',
          taxNo: 'TA20181013348',
          otherDetails:
            'Central Azerbaijanian Manat AI Division Money Market Account Global next-generation Steel California Auto Loan Account',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174199,
          createdBy: 'Waino Lindgren',
          createdOn: '2018-10-12T13:27:41.5315054+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWY=',
          userName: null
        },
        {
          code: 'CS20181013349',
          companyName: 'Harris, Ritchie and Schmidt',
          title: 'Mr.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Mr..  ',
          displayName: 'Balistreri, Breitenberg and Romaguera',
          billingAddress: '9753 Mante Turnpike, West Bobbie, Morocco',
          shippingAddress: '63850 Rashad Station, Nienowstad, Poland',
          email: 'Leanna_Brekke5@hotmail.com',
          phone: '1-876-769-7224 x2839',
          mobile: '443-490-5240 x90818',
          fax: '1-481-408-9154 x86786',
          taxNo: 'TA20181013350',
          otherDetails:
            'Oklahoma copy Solutions TCP Cotton British Indian Ocean Territory (Chagos Archipelago) Sleek wireless XML Metal',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174200,
          createdBy: 'Neva West',
          createdOn: '2018-10-12T13:27:41.531579+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWc=',
          userName: null
        },
        {
          code: 'CS20181013351',
          companyName: 'Davis, Erdman and Schneider',
          title: 'Miss',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Miss.  ',
          displayName: 'Stracke, Vandervort and Labadie',
          billingAddress: '42774 Warren Via, Rebeccastad, Rwanda',
          shippingAddress: '96794 Lessie Fords, South Mayefort, Greenland',
          email: 'Alisha_Jerde@gmail.com',
          phone: '1-331-309-4471 x417',
          mobile: '546.725.8522',
          fax: '(859) 346-4359',
          taxNo: 'TA20181013352',
          otherDetails:
            'Fantastic Frozen Table De-engineered Knoll Coordinator relationships withdrawal Communications exuding Arkansas Awesome Metal Gloves',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174201,
          createdBy: 'Juston Keebler',
          createdOn: '2018-10-12T13:27:41.5316485+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWg=',
          userName: null
        },
        {
          code: 'CS20181013353',
          companyName: 'Schulist, Quigley and Hansen',
          title: 'Ms.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Ms..  ',
          displayName: 'Schaden, Lockman and Blanda',
          billingAddress: '24208 Eve Turnpike, North Rossie, Jordan',
          shippingAddress: '8906 Ondricka Valley, West Kyle, South Africa',
          email: 'Monica.Waelchi62@gmail.com',
          phone: '495-991-0923 x502',
          mobile: '1-362-329-5033',
          fax: '(454) 770-3310',
          taxNo: 'TA20181013354',
          otherDetails:
            'back-end Refined Frozen Salad Corporate content-based Auto Loan Account Group withdrawal middleware West Virginia deposit',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174202,
          createdBy: 'Haven Donnelly',
          createdOn: '2018-10-12T13:27:41.531722+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaWk=',
          userName: null
        }
      ]
    };

    const result = <MetaDataItem<any>>mergeData(original, latest, {
      valueSelector: (p: string, o: any, l: any) =>
        p === 'pageIndex' ? Math.max(o, l) : l
    });

    expect(result.items.length).toBe(
      original.items.length + latest.items.length
    );

    expect(result.pageSize).toBe(latest.pageSize);
    expect(result.totalItems).toBe(latest.totalItems);
    expect(result.totalPage).toBe(latest.totalPage);
    expect(result.pageIndex).toBe(
      Math.max(original.pageIndex, latest.pageIndex)
    );
  });

  test('merge object update item in array with thesame id', () => {
    const original = {
      includeArchived: false,
      searchText: null,
      orderBy: null,
      direction: 'Asc',
      pageIndex: 10,
      pageSize: 10,
      totalItems: 9992,
      totalPage: 1000,
      items: [
        {
          code: 'CSYY100001',
          companyName: 'chdhfjfjgfgjfj',
          title: null,
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: '.  ',
          displayName: 'tdrydrydrydr',
          billingAddress: null,
          shippingAddress: null,
          email: null,
          phone: null,
          mobile: null,
          fax: null,
          taxNo: null,
          otherDetails: null,
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 1,
          createdBy: 'Tuan',
          createdOn: '2018-10-12T03:34:54.2364397+00:00',
          updatedBy: 'Tuan',
          updatedOn: '2018-10-12T03:35:20.8541415+00:00',
          isDeleted: false,
          rowVersion: 'AAAAAAADG1U=',
          userName: null
        },
        {
          code: 'CS20181013327',
          companyName: 'Dibbert, Funk and Cremin',
          title: 'Miss',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Miss.  ',
          displayName: 'Strosin, Wuckert and Deckow',
          billingAddress: '45022 Muller Extension, Lucianoton, Togo',
          shippingAddress: '879 Yundt Springs, Nitzscheside, Tokelau',
          email: 'Wilburn88@hotmail.com',
          phone: '543.345.2302 x02094',
          mobile: '1-708-960-8951',
          fax: '1-322-862-3812 x406',
          taxNo: 'TA20181013328',
          otherDetails:
            'zero administration invoice connecting Heights interactive content Squares bluetooth invoice back-end',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174189,
          createdBy: "Jodie O'Connell",
          createdOn: '2018-10-12T13:27:41.5307907+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaVw=',
          userName: null
        },
        {
          code: 'CS20181013329',
          companyName: 'Stanton, Monahan and Gorczany',
          title: 'Mrs.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Mrs..  ',
          displayName: 'Turner, Gusikowski and Cronin',
          billingAddress: '1838 Jairo Union, Boehmport, Macao',
          shippingAddress:
            '1684 Madie Union, Lueilwitzborough, Russian Federation',
          email: 'Ally_Cummerata31@gmail.com',
          phone: '526-233-8932 x52496',
          mobile: '1-232-389-5217 x3238',
          fax: '(247) 304-5150 x9353',
          taxNo: 'TA20181013330',
          otherDetails:
            "Pa'anga primary Garden, Clothing & Tools one-to-one zero defect Shoes Incredible Granite Chair 5th generation TCP circuit",
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174190,
          createdBy: 'Leland Bahringer',
          createdOn: '2018-10-12T13:27:41.5308604+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaV0=',
          userName: null
        },
        {
          code: 'CS20181013331',
          companyName: 'Bode, Marks and Schamberger',
          title: 'Mrs.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Mrs..  ',
          displayName: 'Konopelski, Lehner and Jaskolski',
          billingAddress: '58795 Schamberger Mill, Leuschketown, Niger',
          shippingAddress:
            '350 Aurelie Creek, Pouroshaven, Trinidad and Tobago',
          email: 'Gino.White38@yahoo.com',
          phone: '1-587-480-9850',
          mobile: '663-556-8274 x941',
          fax: '(886) 228-9503 x33228',
          taxNo: 'TA20181013332',
          otherDetails:
            'grey pink whiteboard Games parse Strategist XML invoice Mountains pixel',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174191,
          createdBy: 'Ally Mills',
          createdOn: '2018-10-12T13:27:41.5309288+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaV4=',
          userName: null
        },
        {
          code: 'CS20181013333',
          companyName: 'Satterfield, Altenwerth and Bartell',
          title: 'Ms.',
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: 'Ms..  ',
          displayName: 'Balistreri, Schultz and Bashirian',
          billingAddress: '692 Ottilie Track, VonRuedenchester, Malta',
          shippingAddress: '2177 Orn Park, Hesselhaven, Yemen',
          email: 'Halie_Abbott67@hotmail.com',
          phone: '936.816.1040',
          mobile: '335.790.9959',
          fax: '487-277-9433 x744',
          taxNo: 'TA20181013334',
          otherDetails:
            'silver synergy Cordoba Oro protocol virtual Investment Account bandwidth California reciprocal Ghana',
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 174192,
          createdBy: 'Nikolas Jakubowski',
          createdOn: '2018-10-12T13:27:41.5309972+00:00',
          updatedBy: null,
          updatedOn: null,
          isDeleted: false,
          rowVersion: 'AAAAAAAHaV8=',
          userName: null
        }
      ]
    };

    const latest = {
      includeArchived: false,
      searchText: null,
      orderBy: null,
      direction: 'Asc',
      pageIndex: 10,
      pageSize: 10,
      totalItems: 9992,
      totalPage: 1000,
      items: [
        {
          code: 'CSYY100001',
          companyName: 'Hoang Bao Duy',
          title: null,
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: '.  ',
          displayName: 'tdrydrydrydr',
          billingAddress: null,
          shippingAddress: null,
          email: null,
          phone: null,
          mobile: null,
          fax: null,
          taxNo: null,
          otherDetails: null,
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 1,
          createdBy: 'Tuan',
          createdOn: '2018-10-12T03:34:54.2364397+00:00',
          updatedBy: 'Tuan',
          updatedOn: '2018-10-12T03:35:20.8541415+00:00',
          isDeleted: false,
          rowVersion: 'AAAAAAADG1U=',
          userName: null
        },
        {
          code: 'CSYY100001',
          companyName: 'HBD',
          title: null,
          firstName: null,
          middleName: null,
          lastName: null,
          fullName: '.  ',
          displayName: 'tdrydrydrydr',
          billingAddress: null,
          shippingAddress: null,
          email: null,
          phone: null,
          mobile: null,
          fax: null,
          taxNo: null,
          otherDetails: null,
          accountReceivableId: null,
          accountPayableId: null,
          defaultPaymentTermId: null,
          maximumReceivable: null,
          maximumReceivableDisabled: true,
          id: 2,
          createdBy: 'Tuan',
          createdOn: '2018-10-12T03:34:54.2364397+00:00',
          updatedBy: 'Tuan',
          updatedOn: '2018-10-12T03:35:20.8541415+00:00',
          isDeleted: false,
          rowVersion: 'AAAAAAADG1U=',
          userName: null
        }
      ]
    };

    const result = <MetaDataItem<any>>mergeData(original, latest, {
      valueSelector: (p: string, o: any, l: any) =>
        p === 'pageIndex' ? Math.max(o, l) : l
    });

    expect(result.items.length).toBe(original.items.length + 1);
    expect(result.pageSize).toBe(latest.pageSize);
    expect(result.totalItems).toBe(latest.totalItems);
    expect(result.totalPage).toBe(latest.totalPage);
    expect(result.pageIndex).toBe(
      Math.max(original.pageIndex, latest.pageIndex)
    );
    expect(result.items.find(i => i.id === 1).companyName).toBe(
      'Hoang Bao Duy'
    );
    expect(result.items.find(i => i.id === 2).companyName).toBe('HBD');
  });

  test('MergeData merge 2 Array', () => {
    const original = [{ id: 1, name: 'Duy' }];
    const latest = [{ id: 1, name: 'Hoang' }];

    const result = mergeData(original, latest);
    expect(result).toMatchObject(latest);
  });

  test('MergeData update status in Array', () => {
    const original = [{ id: 1, name: 'Duy', status: 'new' }];
    const latest = [{ id: 1, status: 'update' }];

    const result = mergeData(original, latest);

    expect(result && result[0].status).toBe('update');
  });

  test('MergeData with null latest ', () => {
    const original = [{ id: 1, name: 'Duy', status: 'new' }];
    const latest = undefined;

    const result = mergeData(original, latest);
    expect(result).toBe(original);
  });

  test('MergeData with null original ', () => {
    const original = undefined;
    const latest = [{ id: 1, name: 'Duy', status: 'new' }];

    const result = mergeData(original, latest);
    expect(result).toBe(latest);
  });
});

describe('Test RemoveData', () => {
  test('Remove item in array by id', () => {
    const defaultState = { data: { items: [{ id: 1, name: 'Steven' }] } };
    const rs = removeItems(defaultState.data.items, { id: 1 });
    expect(rs.length).toBe(0);
  });

  test('Remove item in array by array of id', () => {
    const defaultState = { data: { items: [{ id: 1, name: 'Steven' }] } };
    const rs = removeItems(defaultState.data.items, [{ id: 1 }]);
    expect(rs.length).toBe(0);
  });

  test('Remove item with undefined original', () => {
    const defaultState = { data: { items: undefined } };
    const rs = removeItems(defaultState.data.items, [{ id: 1 }]);
    expect(rs).toMatchObject([]);
  });
});
